name: cue

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt
    - name: Lint with flake8
      run: |
        python -m flake8 .
    - name: Install cue
      run: |
        curl -LO https://github.com/cuelang/cue/releases/download/v0.2.2/cue_0.2.2_Linux_x86_64.tar.gz
        tar xzf cue_0.2.2_Linux_x86_64.tar.gz
    - name: Test with pytest
      run: |
        CUE_EXE=${PWD}/cue python -m pytest -v -rf tests
